ausentismos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r"^$", AusentismoView.as_view(), name="ausentismo_listado"),
    url(r"^nuevo/$", AusentismoCreateView.as_view(), name="ausentismo_nuevo"),
    url(r"^editar/(?P<id>\d+)/$", AusentismoEditView.as_view(), name="ausentismo_editar"),
    url(r"^detalles/(?P<id>\d+)/$", AusentismoVerView.as_view(), name="ausentismo_detalles"),
    url(r"^eliminar/(?P<id>\d+)/$", ausentismo_eliminar, name="ausentismo_eliminar"),
    url(r"^historial/(?P<id>\d+)/$", AusentismoHistorialView.as_view(), name="ausentismo_historial"),
    url(r"^ausencias_cargar_control/(?P<id>\d+)/$", SeguimControlCreateView.as_view(), name="ausencias_cargar_control"),
    url(r"^patologia/$", PatologiaView.as_view(), name="patologia_listado"),
    url(r"^patologia/nuevo/$", PatologiaCreateView.as_view(), name="patologia_nuevo"),
    url(r"^patologia/editar/(?P<id>\d+)/$", PatologiaEditView.as_view(), name="patologia_editar"),
    url(r"^patologia/baja_alta/(?P<id>\d+)/$", patologia_baja_alta, name="patologia_baja_alta"),
    url(r"^diagnostico/$", DiagnosticoView.as_view(), name="diagnostico_listado"),
    url(r"^diagnostico/nuevo/$", DiagnosticoCreateView.as_view(), name="diagnostico_nuevo"),
    url(r"^diagnostico/editar/(?P<id>\d+)/$", DiagnosticoEditView.as_view(), name="diagnostico_editar"),
    # url(r'^diagnostico/detalles/(?P<id>\d+)/$', ARTVerView.as_view(), name="patologia_detalles"),
    url(r"^diagnostico/baja_alta/(?P<id>\d+)/$", diagnostico_baja_alta, name="diagnostico_baja_alta"),
    url(r"^ausencias_importar/$", ausencias_importar, name="ausencias_importar"),
    url(r"^generar_informe/$", generarInforme, name="generar_informe"),
    url(r"^generar_informe_individual/(?P<id>\d+)/$", generarInformeIndividual, name="generar_informe_individual"),
    url(r"^imprimir_informe/$", imprimir_informe, name="imprimir_informe"),
    url(r"^imprimir_ausentismo/(?P<id>\d+)/$", imprimir_ausentismo, name="imprimir_ausentismo"),
    url(r"^imprimir_historial/(?P<id>\d+)/$", imprimir_historial, name="imprimir_historial"),
    url(r"^ausentismo_eliminar_masivo/$", ausentismo_eliminar_masivo, name="ausentismo_eliminar_masivo"),
]

general/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from .views import *
urlpatterns = [
    url(r'^$', PrincipalView.as_view(), name='principal'),
    url(r'^buscarDatosAPICUIT/$', buscarDatosAPICUIT, name='buscarDatosAPICUIT'),
    url(r'^buscarDatosEntidad/$', buscarDatosEntidad, name='buscarDatosEntidad'),
    url(r'^recargar_empleados/$', recargar_empleados, name='recargar_empleados'),
    url(r'^recargar_empleados_empresa/(?P<id>\d+)/$', recargar_empleados_empresa, name='recargar_empleados_empresa'),
    url(r'^recargar_empresas_agrupamiento/(?P<id>\d+)/$', recargar_empresas_agrupamiento, name='recargar_empresas_agrupamiento'),
    url(r'^recargar_medicos/$', recargar_medicos, name='recargar_medicos'),
    url(r'^recargar_diagnosticos/$', recargar_diagnosticos, name='recargar_diagnosticos'),
    url(r'^recargar_patologias/$', recargar_patologias, name='recargar_patologias'),

    url(r'^turnos/$', TurnosView.as_view(),name="turnos_listado"),
    url(r'^turnos/nuevo/$', TurnosCreateView.as_view(), name="turnos_nuevo"),
    url(r'^turnos/nuevo_rapido/$', TurnosLightCreateView.as_view(), name="turnos_nuevo_rapido"),
    url(r'^turnos/editar/(?P<id>\d+)/$', TurnosEditView.as_view(), name="turnos_editar"),
    url(r'^turnos/eliminar/(?P<id>\d+)/$', turno_eliminar, name='turnos_eliminar'),
    url(r'^turnos/estado/(?P<id>\d+)/(?P<estado>\d+)$', turno_estado, name='turnos_estado'),
    url(r'^turnos/detalles/(?P<id>\d+)/$', TurnosVerView.as_view(), name="turnos_detalles"),    

    url(r'^configuracion_editar/(?P<id>\d+)/$', ConfiguracionEditView.as_view(), name="configuracion_editar"),
    
]

laboralsalud/urls.py
# -*- coding: utf-8 -*-
"""laboralsalud URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import login,logout,volverHome


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^entidades/', include('entidades.urls')),
    url(r'^ausentismos/', include('ausentismos.urls')),
    url(r'^reportes/', include('reportes.urls')),
    url(r'^usuarios/', include('usuarios.urls')),
    url(r'^', include('general.urls')),
    url(r'^login/$', login,name="login"),
    url(r'^logout/$', logout,name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler500 = volverHome
handler404 = volverHome

ausentismos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models.signals import post_save, post_delete
from django.db.models import Q
from django.dispatch import receiver

from django.db import models

from ausentismos.managers import AusentismosActivos
from laboralsalud.utilidades import *
from entidades.models import ent_empleado, ent_medico_prof, ent_empresa


class aus_patologia(models.Model):
    id = models.AutoField(primary_key=True, db_index=True)
    codigo = models.CharField(max_length=200, blank=True, null=True)
    patologia = models.CharField(max_length=200)
    baja = models.BooleanField(default=False)

    class Meta:
        db_table = "aus_patologia"
        ordering = [
            "patologia",
        ]

    def __unicode__(self):
        return "%s" % (self.patologia.upper())

    def get_patologia(self):
        entidad = "%s" % self.patologia.upper()
        return entidad.upper()


class aus_diagnostico(models.Model):
    id = models.AutoField(primary_key=True, db_index=True)
    codigo = models.CharField(max_length=200, blank=True, null=True)
    diagnostico = models.CharField(max_length=200)
    baja = models.BooleanField(default=False)

    class Meta:
        db_table = "aus_diagnostico"
        ordering = [
            "diagnostico",
        ]

    def __unicode__(self):
        return "%s" % (self.diagnostico.upper())

        def get_diagnostico(self):
            entidad = "%s" % self.diagnostico.upper()
            return entidad.upper()


# Tabla de la Base de Configuracion


class ausentismo(models.Model):
    empleado = models.ForeignKey(
        "entidades.ent_empleado",
        verbose_name="Empleado",
        db_column="empleado",
        blank=True,
        null=True,
        related_name="aus_empleado",
        on_delete=models.PROTECT,
    )
    tipo_ausentismo = models.IntegerField("Ausentismo", choices=TIPO_AUSENCIA, blank=True, null=True)
    tipo_control = models.CharField("Tipo Control", choices=TIPO_CONTROL, max_length=1, blank=True, null=True)
    aus_control = models.CharField("¿Asistió a Control?", max_length=1, default="S")
    aus_fcontrol = models.DateField("Fecha Próx.Control", blank=True, null=True)
    aus_certificado = models.CharField("¿Presenta Certificado?", max_length=1, default="N")
    # aus_fcertif = models.DateField("Fecha Certificado", blank=True, null=True)
    # aus_fentrega_certif = models.DateField("Fecha Entrega Certif.", blank=True, null=True)

    aus_fcrondesde = models.DateField("Cronológica Desde", blank=True, null=True)
    aus_fcronhasta = models.DateField("Cronológica Hasta", blank=True, null=True)
    aus_diascaidos = models.IntegerField("Días Caídos", blank=True, null=True)
    aus_diasjustif = models.IntegerField("Días Justificados", blank=True, null=True)
    aus_freintegro = models.DateField("F.Reintegro", blank=True, null=True)
    aus_falta = models.DateField("Fecha Alta", blank=True, null=True)
    aus_tipo_alta = models.IntegerField("Tipo Alta", choices=TIPO_ALTA, blank=True, null=True)
    aus_corta_certificado = models.CharField(max_length=1, default="N")
    # aus_frevision = models.DateField(u'Fecha Próx.Control',blank=True, null=True)
    aus_medico = models.ForeignKey(
        "entidades.ent_medico_prof",
        verbose_name="Médico Tratante/ART",
        db_column="aus_medico",
        blank=True,
        null=True,
        related_name="aus_medico",
        on_delete=models.SET_NULL,
    )
    aus_grupop = models.ForeignKey(
        aus_patologia,
        verbose_name="Grupo Patológico",
        db_column="aus_grupop",
        blank=True,
        null=True,
        related_name="aus_grupop",
        on_delete=models.SET_NULL,
    )
    aus_diagn = models.ForeignKey(
        aus_diagnostico,
        verbose_name="Diagnóstico",
        db_column="aus_diagn",
        blank=True,
        null=True,
        related_name="aus_diagn",
        on_delete=models.SET_NULL,
    )

    art_tipo_accidente = models.IntegerField("Tipo Accidente/Enfermedad", choices=TIPO_ACCIDENTE, blank=True, null=True)
    art_ndenuncia = models.CharField("Nº Denuncia", max_length=50, blank=True, null=True)
    art_faccidente = models.DateField("Fecha Accidente", blank=True, null=True)
    art_fdenuncia = models.DateField("Fecha Denuncia", blank=True, null=True)

    observaciones = models.TextField("Observaciones", blank=True, null=True)
    descr_altaparc = models.TextField("Descr.Alta Parcial", blank=True, null=True)
    detalle_acc_art = models.TextField("Detalle Acc.ART", blank=True, null=True)
    estudios_partic = models.TextField("Estudios Particulares", blank=True, null=True)
    estudios_art = models.TextField("Estudios ART", blank=True, null=True)
    recalificac_art = models.TextField("Recalificación ART", blank=True, null=True)

    plan_accion = models.TextField("Observaciones", blank=True, null=True)
    resumen_patologias = models.TextField(u"Resúmen Patologías", blank=True, null=True)
    tareas_diferentes = models.CharField("¿Tareas Diferentes?", max_length=1, default="N")
    preocupacional = models.TextField("Preocupacional", blank=True, null=True)

    empresa = models.ForeignKey(
        ent_empresa,
        verbose_name="Empresa",
        db_column="empresa",
        blank=True,
        null=True,
        related_name="aus_empresa",
        on_delete=models.SET_NULL,
    )


    baja = models.BooleanField(default=False)
    fecha_creacion = models.DateField(auto_now_add=True)
    fecha_modif = models.DateField(auto_now=True)
    usuario_carga = models.ForeignKey(
        "usuarios.UsuUsuario",
        db_column="usuario_carga",
        blank=True,
        null=True,
        related_name="aus_usuario_carga",
        on_delete=models.SET_NULL,
    )

    objects = models.Manager()
    ausentismos_activos = AusentismosActivos()
    class Meta:
        db_table = "ausentismo"
        ordering = ["-aus_fcrondesde", "-aus_fcronhasta", "empresa"]

    def __unicode__(self):
        return "%s - %s (%s)" % (self.pk, self.empleado, self.get_fechas)

    @property
    def get_dias_caidos(self):
        dias = 0
        if self.aus_diascaidos:
            dias = self.aus_diascaidos
        return dias

    @property
    def get_fechas(self):
        desde = None
        hasta = None
        if self.aus_fcrondesde:
            desde = self.aus_fcrondesde.strftime("%d/%m/%Y")
        if self.aus_fcronhasta:
            hasta = self.aus_fcronhasta.strftime("%d/%m/%Y")
        return "%s hasta %s" % (desde, hasta)

    @property
    def get_fcrondesde(self):
        return self.aus_fcrondesde

    @property
    def get_fcronhasta(self):
        return self.aus_fcronhasta

    @property
    def get_proxcontrol(self):
        return self.aus_fcontrol

    @property
    def get_falta(self):
        return self.aus_falta

    @property
    def get_tipo_alta(self):
        return self.get_aus_tipo_alta_display()

    @property
    def get_ultimo_control(self):
        return ausentismo_controles.objects.filter(ausentismo=self).order_by("-fecha").first()


class ausentismo_controles(models.Model):
    id = models.AutoField(primary_key=True, db_index=True)
    ausentismo = models.ForeignKey(
        "ausentismo",
        db_column="ausentismo",
        related_name="control_ausentismo",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    fecha = models.DateField(blank=True, null=True)
    tipo_control = models.CharField("Tipo Control", choices=TIPO_CONTROL, max_length=1, blank=True, null=True)
    # Field name made lowercase.
    detalle = models.TextField(max_length=1000, blank=True, null=True)
    fecha_creacion = models.DateField(auto_now_add=True)
    fecha_modif = models.DateField(auto_now=True)
    usuario_carga = models.ForeignKey(
        "usuarios.UsuUsuario",
        db_column="usuario_carga",
        blank=True,
        null=True,
        related_name="control_usuario_carga",
        on_delete=models.SET_NULL,
    )

    class Meta:
        db_table = "ausentismo_controles"
        ordering = ["fecha", "id"]

    def __unicode__(self):
        return "%s - %s" % (self.fecha, self.detalle)


class ausentismo_controles_patologias(models.Model):
    id = models.AutoField(primary_key=True, db_index=True)
    ausentismo = models.ForeignKey(
        "ausentismo",
        db_column="ausentismo",
        related_name="control_ausentismo_pat",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    fecha = models.DateField(blank=True, null=True)
    # Field name made lowercase.
    detalle = models.TextField(max_length=1000, blank=True, null=True)
    fecha_creacion = models.DateField(auto_now_add=True)
    fecha_modif = models.DateField(auto_now=True)
    usuario_carga = models.ForeignKey(
        "usuarios.UsuUsuario",
        db_column="usuario_carga",
        blank=True,
        null=True,
        related_name="control_pat_usuario_carga",
        on_delete=models.SET_NULL,
    )

    class Meta:
        db_table = "ausentismo_controles_patologias"
        ordering = ["fecha", "id"]

    def __unicode__(self):
        return "%s - %s" % (self.fecha, self.detalle)


def ausentismos_del_dia(request, fecha):
    controles = ausentismo_controles.objects.filter(fecha=fecha).values_list("ausentismo__id", flat=True)
    ausentismos = ausentismo.objects.filter(baja=False, empresa__pk__in=empresas_habilitadas(request)).filter(
        Q(fecha_creacion=fecha) | (Q(id__in=controles))
    )
    return ausentismos


@receiver(post_save, sender=ausentismo, dispatch_uid="eliminar_controles_vacios")
def eliminar_controles_vacios(sender, instance, created, **kwargs):
    if instance:
        controles = ausentismo_controles.objects.filter(ausentismo=instance).filter(
            Q(fecha__isnull=True, detalle__isnull=True) | Q(fecha__isnull=True, detalle="")
        )
        controles.delete()
        # if (not instance.fecha)and(not instance.detalle):

templates/ausentismos/ausentismo_detalle.html
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load filtros_especiales %}

{% block main %}
  <div class="row ">
    <div class="col-xs-12 cerca" >
      <fieldset>
        <legend>DATOS EMPLEADO</legend>
        <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
          <tbody>
            <tr>
              <td  class="titulo">Apellido y Nombre:</td><td colspan="3" id="apellido_y_nombre" class="dato">{{a.empleado.apellido_y_nombre|default_if_none:''}}</td>
            </tr>
            <tr>
              <td class="titulo">Documento:</td><td id="nro_doc" class="dato">{{a.empleado.nro_doc|default_if_none:''}}</td>
              <td class="titulo">Nº Legajo:</td><td id="legajo" class="dato">{{a.empleado.legajo|default_if_none:''}}</td>
            </tr>
            <tr>
              <td class="titulo">Fecha Nacimiento:</td><td id="fecha_nac" class="dato">{{a.empleado.fecha_nac|date:'d/m/Y'}}</td>
              <td class="titulo">Edad:</td><td id="edad" class="dato">{{a.empleado.get_edad|default_if_none:0}} años</td>
            </tr>
            <tr>
              <td  class="titulo">Empresa:</td><td colspan="3" id="empresa" class="dato">{{a.empleado.empresa|default_if_none:''}}</td>
            </tr>
            <tr>
              <td class="titulo">Fecha Ingreso Empresa:</td><td id="empr_fingreso" class="dato">{{a.empleado.empr_fingreso|date:'d/m/Y'}}</td>
              <td class="titulo">Antigüedad Laboral:</td><td id="antig_empresa" class="dato">{{a.empleado.get_antiguedad_empr|default_if_none:0}} años</td>
            </tr>
            <tr>
              <td  class="titulo">Puesto/Cargo:</td><td colspan="3" id="trab_cargo" class="dato">{{a.empleado.trab_cargo|default_if_none:''}}</td>
            </tr>
            <tr>
              <td class="titulo">ART:</td><td colspan="3" id="art" class="dato">{{a.empleado.art|default_if_none:''}}</td>
            </tr>
          </tbody>
        </table>
      </fieldset>
      <fieldset>
        <legend>DATOS AUSENTISMO/CONTROL - {{a.get_tipo_ausentismo_display|default_if_none:''|upper}}
           {% if a.tipo_control %} ( {{a.get_tipo_control_display|default_if_none:''|upper}} ){% endif %}</legend>
        <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
          <tbody>
            {% if a.tipo_ausentismo == 1 or a.tipo_ausentismo >= 4 %}
              <tr>
{#                <td class="titulo">¿Asistió a Control?:</td><td id="empr_fingreso" class="dato">{{a.aus_control|default_if_none:'N'}}</td>#}
                <td class="titulo">Fecha Próx.Control:</td><td id="antig_empresa" class="dato">{{a.get_proxcontrol|date:'d/m/Y'}}</td>
                <td class="titulo"></td><td class="dato"></td>
              </tr>
              <tr>
{#                <td class="titulo">¿Presenta Certificado?:</td><td id="empr_fingreso" class="dato">{{a.aus_certificado|default_if_none:'N'}}</td>#}
{#                <td class="titulo">Fecha Certificado:</td><td id="antig_empresa" class="dato">{{a.aus_fcertif|date:'d/m/Y'}}</td>#}
{#                <td class="titulo">Fecha Entrega Certif.:</td><td id="antig_empresa" class="dato">{{a.aus_fentrega_certif|date:'d/m/Y'}}</td>#}
                <td class="titulo"></td><td class="titulo"></td>
              </tr>
              <tr>
                <td class="titulo">Fecha Desde:</td><td id="antig_empresa" class="dato">{{a.aus_fcrondesde|date:'d/m/Y'}}</td>
                <td class="titulo">Fecha Hasta:</td><td id="antig_empresa" class="dato">{{a.aus_fcronhasta|date:'d/m/Y'}}</td>
                <td class="titulo">Días Caídos:</td><td id="antig_empresa" class="dato">{{a.aus_diascaidos|default_if_none:'0'}} días</td>
                <td class="titulo">Días Justificados:</td><td id="antig_empresa" class="dato">{{a.aus_diasjustif|default_if_none:'0'}} días</td>
              </tr>
              <tr>
                <td class="titulo">Fecha Reintegro:</td><td id="antig_empresa" class="dato">{{a.aus_freintegro|date:'d/m/Y'}}</td>
                <td class="titulo">Fecha Alta:</td><td id="antig_empresa" class="dato">{{a.aus_falta|date:'d/m/Y'}}</td>
                <td class="titulo">Tipo Alta:</td><td id="antig_empresa" class="dato">{{a.get_aus_tipo_alta_display|default_if_none:''}}</td>
                
              </tr>
              <tr>
                
                <td class="titulo">Médico Tratante:</td><td class="dato" colspan="7">{{a.aus_medico|default_if_none:''}}</td>
              </tr>
            {% else %}
              <tr>
                <td class="titulo">Tipo Accidente/Enfermedad</td><td id="empr_fingreso" colspan="3" class="dato">{{a.get_art_tipo_accidente_display|default_if_none:'N'}}</td>
                <td class="titulo">Nº Denuncia:</td><td id="antig_empresa" class="dato">{{a.art_ndenuncia|default_if_none:''}}</td>
                <td class="titulo">Fecha Denuncia:</td><td id="antig_empresa" class="dato">{{a.art_fdenuncia|date:'d/m/Y'}}</td>
              </tr>
              <tr>
                <td class="titulo">Fecha Desde:</td><td id="antig_empresa" class="dato">{{a.aus_fcrondesde|date:'d/m/Y'}}</td>
                <td class="titulo">Fecha Hasta:</td><td id="antig_empresa" class="dato">{{a.aus_fcronhasta|date:'d/m/Y'}}</td>
                <td class="titulo">Días Caídos:</td><td id="antig_empresa" class="dato">{{a.aus_diascaidos|default_if_none:'0'}} días</td>
                <td class="titulo">Fecha Reintegro:</td><td id="antig_empresa" class="dato">{{a.aus_freintegro|date:'d/m/Y'}}</td>
              </tr>
              <tr>
                <td class="titulo">Fecha Próx.Control:</td><td id="antig_empresa" class="dato">{{a.get_proxcontrol|date:'d/m/Y'}}</td>
                <td class="titulo">Fecha Accidente:</td><td id="antig_empresa" class="dato">{{a.art_faccidente|date:'d/m/Y'}}</td>
                <td class="titulo">Fecha Alta:</td><td id="antig_empresa" class="dato">{{a.aus_falta|date:'d/m/Y'}}</td>
                <td class="titulo">Tipo Alta:</td><td id="antig_empresa" class="dato">{{a.aus_tipo_alta|default_if_none:''}}</td>
              </tr>
              <tr>
                <td class="titulo">Médico Tratante:</td><td class="dato" colspan="7">{{a.aus_medico|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if info_sensible %}
            <tr>
              <td class="titulo">Grupo Patológico:</td><td colspan="3" class="dato">{{a.aus_grupop|default_if_none:''}}</td>
              <td class="titulo">Diagnóstico:</td><td class="dato" colspan="3">{{a.aus_diagn|default_if_none:''}}</td>
            </tr>
            <tr>
              <td class="titulo">Fecha Carga:</td><td id="antig_empresa" class="dato">{{a.fecha_creacion|date:'d/m/Y'}}</td>
              <td class="titulo">Usuario:</td><td id="antig_empresa" class="dato">{{a.usuario_carga|default_if_none:''}}</td
              >
              <td class="titulo">Fecha Modificación:</td><td id="antig_empresa" class="dato">{{a.fecha_modif|date:'d/m/Y'}}</td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </fieldset>
      {% if info_sensible %}
          {% if a.plan_accion %}
          <fieldset>
            <legend>PLAN DE ACCIÓN</legend>
            <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
              <tbody>
                  <tr>
                   <td colspan="4" class="dato">{{a.plan_accion|default_if_none:''}}</td>
                  </tr>
              </tbody>
            </table>
          </fieldset>
          {% endif %}
            <fieldset>
        <legend>OTRAS OBSERVACIONES/CONTROLES</legend>
        <div class="row">
        <div style="width: 100%; max-height: 260px; overflow-y: scroll">         
        <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle" >
          <tbody>            
            {% if a.observaciones %}
              <tr>
                <td class="titulo">Información Adicional:</td><td colspan="3" class="dato">{{a.observaciones|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if a.descr_altaparc %}
              <tr>
                <td class="titulo">Descr.Alta Parcial:</td><td colspan="3" class="dato">{{a.descr_altaparc|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if a.detalle_acc_art %}
              <tr>
                <td class="titulo">Detalle Acc.ART:</td><td colspan="3" class="dato">{{a.detalle_acc_art|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if a.estudios_partic %}
              <tr>
                <td width"25%" class="titulo">Estudios Particulares:</td><td colspan="3" class="dato">{{a.estudios_partic|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if a.estudios_art %}
              <tr>
                <td class="titulo">Estudios ART:</td><td colspan="3" class="dato">{{a.estudios_art|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% if a.recalificac_art %}
              <tr>
                <td class="titulo">Recalificación ART:</td><td colspan="3" class="dato">{{a.recalificac_art|default_if_none:''}}</td>
              </tr>
            {% endif %}
            {% for c in controles %}
              <tr>
                <td class="titulo" width="15%">Fecha Control:</td><td class="dato">{{c.fecha|date:'d/m/Y'}}</td>
                <td colspan="2" class="dato">{{c.detalle|default_if_none:''}}</td>
              </tr>
            {% endfor %}
            
          </tbody>
        </table>
      </div>
      </div>
      </fieldset>

      {% if controles_pat %}
      <fieldset>
      <legend>RESUMEN PATOLOGÍA</legend>
        <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
          <tbody>
            {% for cc in controles_pat %}
              <tr>
                <td class="titulo" width="5%">Fecha:</td><td class="dato">{{cc.fecha|date:'d/m/Y'}}</td>
                <td class="dato" width="95%">{{cc.detalle|default_if_none:''}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </fieldset>
      {% endif %}
    {% endif %}
    </div>
  </div>
  <div class="modal-buttons">
    <div class="row">
      <div class="col-xs-6">
        <button data-dismiss="modal" class="btn btn-xs pull-left btn btn-danger" type="button">
        <i class="fa fa-times"></i>Cerrar
        </button>
      </div>
      <div class="col-xs-6">
        <a  class="btn pull-right btn-xs btn-primary" target="_blank" href="{% url 'imprimir_ausentismo' id=a.pk %}" type="button">
        <i class="fa fa-check"></i>Imprimir</a>
      </div>
      
    </div>
  </div>
{% endblock main %}