entidades/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from .views import *
urlpatterns = [
    url(r'^art/$', ARTView.as_view(),name="art_listado"),
    url(r'^art/nuevo/$', ARTCreateView.as_view(), name="art_nuevo"),
    url(r'^art/editar/(?P<id>\d+)/$', ARTEditView.as_view(), name="art_editar"),    
    url(r'^art/detalles/(?P<id>\d+)/$', ARTVerView.as_view(), name="art_detalles"),    
    url(r'^art/baja_alta/(?P<id>\d+)/$', art_baja_alta, name='art_baja_alta'),

    url(r'^cargo/$', CargoView.as_view(),name="cargo_listado"),
    url(r'^cargo/nuevo/$', CargoCreateView.as_view(), name="cargo_nuevo"),
    url(r'^cargo/editar/(?P<id>\d+)/$', CargoEditView.as_view(), name="cargo_editar"),    
    url(r'^cargo/detalles/(?P<id>\d+)/$', CargoVerView.as_view(), name="cargo_detalles"),    
    url(r'^cargo/baja_alta/(?P<id>\d+)/$', cargo_baja_alta, name='cargo_baja_alta'),

    url(r'^especialidad/$', EspecialidadView.as_view(),name="especialidad_listado"),
    url(r'^especialidad/nuevo/$', EspecialidadCreateView.as_view(), name="especialidad_nuevo"),
    url(r'^especialidad/editar/(?P<id>\d+)/$', EspecialidadEditView.as_view(), name="especialidad_editar"),    
    url(r'^especialidad/detalles/(?P<id>\d+)/$', EspecialidadVerView.as_view(), name="especialidad_detalles"),    
    url(r'^especialidad/baja_alta/(?P<id>\d+)/$', especialidad_baja_alta, name='especialidad_baja_alta'),

    url(r'^medico_prof/$', MedProfView.as_view(),name="medico_prof_listado"),
    url(r'^medico_prof/nuevo/$', MedProfCreateView.as_view(), name="medico_prof_nuevo"),
    url(r'^medico_prof/editar/(?P<id>\d+)/$', MedProfEditView.as_view(), name="medico_prof_editar"),    
    url(r'^medico_prof/detalles/(?P<id>\d+)/$', MedProfVerView.as_view(), name="medico_prof_detalles"),    
    url(r'^medico_prof/baja_alta/(?P<id>\d+)/$', medico_prof_baja_alta, name='medico_prof_baja_alta'),

    url(r'^empresa/$', EmpresaView.as_view(),name="empresa_listado"),
    url(r'^empresa/nuevo/$', EmpresaCreateView.as_view(), name="empresa_nuevo"),
    url(r'^empresa/editar/(?P<id>\d+)/$', EmpresaEditView.as_view(), name="empresa_editar"),    
    url(r'^empresa/detalles/(?P<id>\d+)/$', EmpresaVerView.as_view(), name="empresa_detalles"),    
    url(r'^empresa/baja_alta/(?P<id>\d+)/$', empresa_baja_alta, name='empresa_baja_alta'),

    url(r'^empleado/$', EmpleadoView.as_view(),name="empleado_listado"),
    url(r'^empleado/nuevo/$', EmpleadoCreateView.as_view(), name="empleado_nuevo"),
    url(r'^empleado/editar/(?P<id>\d+)/$', EmpleadoEditView.as_view(), name="empleado_editar"),    
    url(r'^empleado/detalles/(?P<id>\d+)/$', EmpleadoVerView.as_view(), name="empleado_detalles"),    
    url(r'^empleado/baja_alta/(?P<id>\d+)/$', empleado_baja_alta, name='empleado_baja_alta'),

    url(r'^empleado_baja_masivo/$',empleado_baja_masivo,name="empleado_baja_masivo"),
    url(r'^empleado_eliminar_masivo/$',empleado_eliminar_masivo,name="empleado_eliminar_masivo"),
    url(r'^empleado_agrupar/$',empleado_agrupar,name="empleado_agrupar"),

    url(r'^importar_empleados/$', importar_empleados,name="importar_empleados"),

    url(r'^empr_agrupamiento/$', EmprAgrupamientoView.as_view(),name="empr_agrupamiento_listado"),
    url(r'^empr_agrupamiento/nuevo/$', EmprAgrupamientoCreateView.as_view(), name="empr_agrupamiento_nuevo"),
    url(r'^empr_agrupamiento/editar/(?P<id>\d+)/$', EmprAgrupamientoEditView.as_view(), name="empr_agrupamiento_editar"),
    url(r'^empr_agrupamiento/baja_alta/(?P<id>\d+)/$', empr_agrupamiento_baja_alta, name='empr_agrupamiento_baja_alta'),

    url(r'^empleado_dt/$', EmpleadoView.as_view(), name="empleado_listado_dt"),

]

general/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from .views import *
urlpatterns = [
    url(r'^$', PrincipalView.as_view(), name='principal'),
    url(r'^buscarDatosAPICUIT/$', buscarDatosAPICUIT, name='buscarDatosAPICUIT'),
    url(r'^buscarDatosEntidad/$', buscarDatosEntidad, name='buscarDatosEntidad'),
    url(r'^recargar_empleados/$', recargar_empleados, name='recargar_empleados'),
    url(r'^recargar_empleados_empresa/(?P<id>\d+)/$', recargar_empleados_empresa, name='recargar_empleados_empresa'),
    url(r'^recargar_empresas_agrupamiento/(?P<id>\d+)/$', recargar_empresas_agrupamiento, name='recargar_empresas_agrupamiento'),
    url(r'^recargar_medicos/$', recargar_medicos, name='recargar_medicos'),
    url(r'^recargar_diagnosticos/$', recargar_diagnosticos, name='recargar_diagnosticos'),
    url(r'^recargar_patologias/$', recargar_patologias, name='recargar_patologias'),

    url(r'^turnos/$', TurnosView.as_view(),name="turnos_listado"),
    url(r'^turnos/nuevo/$', TurnosCreateView.as_view(), name="turnos_nuevo"),
    url(r'^turnos/nuevo_rapido/$', TurnosLightCreateView.as_view(), name="turnos_nuevo_rapido"),
    url(r'^turnos/editar/(?P<id>\d+)/$', TurnosEditView.as_view(), name="turnos_editar"),
    url(r'^turnos/eliminar/(?P<id>\d+)/$', turno_eliminar, name='turnos_eliminar'),
    url(r'^turnos/estado/(?P<id>\d+)/(?P<estado>\d+)$', turno_estado, name='turnos_estado'),
    url(r'^turnos/detalles/(?P<id>\d+)/$', TurnosVerView.as_view(), name="turnos_detalles"),    

    url(r'^configuracion_editar/(?P<id>\d+)/$', ConfiguracionEditView.as_view(), name="configuracion_editar"),
    
]

laboralsalud/urls.py
# -*- coding: utf-8 -*-
"""laboralsalud URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import login,logout,volverHome


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^entidades/', include('entidades.urls')),
    url(r'^ausentismos/', include('ausentismos.urls')),
    url(r'^reportes/', include('reportes.urls')),
    url(r'^usuarios/', include('usuarios.urls')),
    url(r'^', include('general.urls')),
    url(r'^login/$', login,name="login"),
    url(r'^logout/$', logout,name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler500 = volverHome
handler404 = volverHome

entidades/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.widgets import TextInput

from entidades.models import (
    ent_art,
    ent_cargo,
    ent_especialidad,
    ent_medico_prof,
    ent_empleado,
    ent_empresa_agrupamiento,
)
from general.validators import validar_fecha_nacimiento
from laboralsalud.utilidades import *


class ARTForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    codigo = forms.CharField(required=True)

    class Meta:
        model = ent_art
        exclude = ["id", "fecha_creacion", "fecha_modif", "usuario_carga"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(ARTForm, self).__init__(*args, **kwargs)


class CargoForm(forms.ModelForm):
    class Meta:
        model = ent_cargo
        exclude = ["id", "baja"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(CargoForm, self).__init__(*args, **kwargs)


class EspecialidadForm(forms.ModelForm):
    class Meta:
        model = ent_especialidad
        exclude = ["id", "baja"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(EspecialidadForm, self).__init__(*args, **kwargs)


class MedProfForm(forms.ModelForm):
    apellido_y_nombre = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    cuit = forms.IntegerField(
        label="CUIT",
        required=False,
        widget=PostPendWidgetBuscar(
            attrs={"class": "form-control"},
            base_widget=TextInput,
            data='<i class="fa fa-search" aria-hidden="true"></i>',
            tooltip=u"Buscar datos y validar CUIT en AFIP",
        ),
    )
    nro_doc = forms.IntegerField(label=u"Documento", required=False)
    cod_postal = forms.IntegerField(label="CP", required=False)
    observaciones = forms.CharField(
        label="Observaciones / Datos adicionales",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 5}),
        required=False,
    )
    tipo_form = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = ent_medico_prof
        exclude = ["id", "fecha_creacion", "fecha_modif", "usuario_carga"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(MedProfForm, self).__init__(*args, **kwargs)

    def clean(self):
        cuit = self.cleaned_data.get("cuit")
        if cuit:
            if not validar_cuit(str(cuit)):
                raise forms.ValidationError(
                    "El Nº de CUIT ingresado es incorrecto! Verifique."
                )

        tipo_form = self.cleaned_data.get("tipo_form")
        if tipo_form == "ALTA":
            if cuit:
                try:
                    entidad = ent_medico_prof.objects.filter(cuit=cuit)
                    if entidad:
                        raise forms.ValidationError(
                            "El Nº de CUIT ingresado ya existe en el Sistema! Verifique."
                        )
                except ent_medico_prof.DoesNotExist:
                    # because we didn't get a match
                    pass
        return self.cleaned_data


class EmpresaForm(forms.ModelForm):
    cuit = forms.IntegerField(
        label="CUIT",
        required=False,
        widget=PostPendWidgetBuscar(
            attrs={"class": "form-control", "autofocus": "autofocus"},
            base_widget=TextInput,
            data='<i class="fa fa-search" aria-hidden="true"></i>',
            tooltip=u"Buscar datos y validar CUIT en AFIP",
        ),
    )
    cod_postal = forms.IntegerField(label="CP", required=False)
    observaciones = forms.CharField(
        label="Observaciones / Datos adicionales",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 5}),
        required=False,
    )
    razon_social = forms.CharField(required=True)
    codigo = forms.CharField(required=True)
    tipo_form = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = ent_empresa
        exclude = ["id", "fecha_creacion", "fecha_modif", "usuario_carga"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(EmpresaForm, self).__init__(*args, **kwargs)


class TrabajoModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_cargo()


class EmpleadoForm(forms.ModelForm):
    apellido_y_nombre = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    nro_doc = forms.IntegerField(label=u"Documento", required=True)
    cod_postal = forms.IntegerField(label="CP", required=False)
    observaciones = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 10}),
        required=False,
    )
    fecha_nac = forms.DateField(
        label=u"Fecha Nacim.",
        required=True,
        widget=forms.DateInput(attrs={"class": "form-control datepicker"}),
        validators=[validar_fecha_nacimiento],
    )
    empr_fingreso = forms.DateField(
        label=u"F.Ingreso.",
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control datepicker"}),
    )
    empr_antig = forms.CharField(
        label=u"Antig.(años)",
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
        required=False,
    )
    trab_fingreso = forms.DateField(
        label=u"F.Ingreso",
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control datepicker"}),
    )
    trab_antig = forms.CharField(
        label=u"Antig.(años)",
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
        required=False,
    )
    trab_fbaja = forms.DateField(
        label=u"Fecha Baja",
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control datepicker"}),
    )
    trab_preocup_conclus = forms.CharField(
        label=u"Conclusión Preocupacional",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_factores_riesgo = forms.CharField(
        label=u"Factores de Riesgo a lo que está Expuesto",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_tareas_dif_det = forms.CharField(
        label=u"Descripción Tareas Diferentes",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_anteriores = forms.CharField(
        label=u"Trabajos Anteriores",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_antecedentes = forms.CharField(
        label=u"Antecedentes Patológicos",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_accidentes = forms.CharField(
        label=u"Accidentes ART",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_vacunas = forms.CharField(
        label=u"Vacunas",
        widget=forms.Textarea(attrs={"class": "form-control2", "rows": 2}),
        required=False,
    )
    trab_preocupac = forms.ChoiceField(
        label="¿Preocupacional?", choices=SINO, required=True, initial="N"
    )
    empresa = forms.ModelChoiceField(
        label="Empresa", queryset=ent_empresa.objects.filter(baja=False), required=True
    )
    trab_cargo = TrabajoModelChoiceField(
        label=u"Puesto de Trabajo",
        queryset=ent_cargo.objects.filter(baja=False),
        required=False,
    )
    tipo_form = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = ent_empleado
        exclude = [
            "id",
            "fecha_creacion",
            "fecha_modif",
            "usuario_carga",
            "trab_armas",
            "trab_tareas_dif",
        ]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(EmpleadoForm, self).__init__(*args, **kwargs)
        self.fields["empresa"].queryset = ent_empresa.objects.filter(
            baja=False, pk__in=empresas_habilitadas(request)
        )

    def clean(self):
        trab_preocupac = self.cleaned_data.get("trab_preocupac")
        trab_preocup_fecha = self.cleaned_data.get("trab_preocup_fecha")
        if (trab_preocupac == "S") and (not trab_preocup_fecha):
            self.add_error("trab_preocup_fecha", u"¡Debe cargar una Fecha!")

        trab_fingreso = self.cleaned_data.get("trab_fingreso")
        trab_fbaja = self.cleaned_data.get("trab_fbaja")
        empr_fingreso = self.cleaned_data.get("empr_fingreso")

        if trab_fingreso:
            if date.today() < trab_fingreso:
                self.add_error("trab_fingreso", u"¡Verifique las Fechas!")

        if empr_fingreso:
            if date.today() < empr_fingreso:
                self.add_error("empr_fingreso", u"¡Verifique las Fechas!")

        if trab_fingreso and trab_fbaja:
            if trab_fingreso > trab_fbaja:
                self.add_error("trab_fbaja", u"¡Verifique las Fechas!")

        nro_doc = self.cleaned_data.get("nro_doc")
        tipo_form = self.cleaned_data.get("tipo_form")
        empresa = self.cleaned_data.get("empresa")

        if tipo_form == "ALTA":
            cant = ent_empleado.objects.filter(nro_doc=nro_doc, empresa=empresa).count()
            if cant > 0:
                raise forms.ValidationError(
                    "¡El Empleado ya existe en el sistema!<br>(está asignado a la empresa %s) Verifique."
                    % empresa
                )

        if self._errors:
            raise forms.ValidationError(

templates/entidades/agrupamiento_empleados_form.html
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load humanize %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/comprobantes.css'%}?{% now "Ymd"%}" type="text/css" >
{% endblock %}

  <div id="enviando" class="cargando" >
    <span class="cargando-txt">ENVIANDO...</span>
    <img class="cargando-img" src="{% static 'img/loading-bars.svg' %}">
  </div>

<div class="modal-dialog modal-content">
               <div class="modal-wrapper">
                 <div data-dismiss="modal" class="close-modal">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                        </div>
                 <div class="modal-head">
                        AGRUPAMIENTO EMPLEADOS
                </div>
                <div id="form-container">
                <form role="form" autocomplete="off" class="form" method="POST" action="{% url 'empleado_agrupar' %}" id="form-empleado_agrupar">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="col-xs-12">
                      <div class="row">
                        <div class="col-sm-2">{% bootstrap_field form.fecha %}</div>
                        <div class="col-sm-10">{% bootstrap_field form.empresa %}</div>
                     </div>
                    </div>
                </div>
                <div class="modal-buttons">
                      <div class="row">
                          <div class="col-xs-12">
                            <button data-dismiss="modal" class="btn btn-xs pull-left btn btn-danger" type="button">
                                <i class="fa fa-times"></i>Cancelar</button>
                                <button id="aceptar" type="submit" class="btn pull-right btn-xs btn-primary"><i class="fa fa-check"></i>Aceptar</button>
                          </div>
                      </div>
                 </div>
                </form>
                 </div>
          </div>
     <script type="text/javascript">
          $("#enviando").hide();
          $.fn.datepicker.dates['es'] = {
    days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
    daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa", "Do"],
    months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    today: "Hoy"
  };

 $('.datepicker').datepicker({
        format: "dd/mm/yyyy",
        language: "es",
        autoclose: true,
        todayHighlight: true
  });

  $('.datepicker').each(function(){
      $(this).datepicker();
  });
  const userAgent = navigator.userAgent.toLowerCase();
  const isTablet = /(ipad|tablet|(android(?!.*mobile))|(windows(?!.*phone)(.*touch))|kindle|playbook|silk|(puffin(?!.*(IP|AP|WP))))/.test(userAgent);

  if (isTablet==false) {
  $("#id_empresa").chosen({
      no_results_text: "Empresa inexistente...",
      placeholder_text_single:"Seleccione una Empresa",
      allow_single_deselect: true,
      width:"100%",
  });
  };


    </script>



</div>

templates/entidades/art_detalle.html
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block main %}    
  
<div class=" col-sm-12 "> 
  <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
    <tbody>
    <tr>
      <td  class="titulo">Nombre:</td><td colspan="3">{{art.nombre|default_if_none:''}}</td>
    </tr>
    <tr>
      <td class="titulo">Prestador:</td><td colspan="3">{{art.prestador|default_if_none:''}}</td>
    </tr>
    <tr>
      <td class="titulo">Documento:</td><td>{{entidad.get_tipo_doc_display|default_if_none:''}} {{entidad.nro_doc|default_if_none:''}}</td>
      <td class="titulo">CUIT/CUIL:</td><td>{{entidad.fact_cuit|default_if_none:''}}</td>
    </tr>
    <tr>
      
    </tr>
    <tr>
      <td class="titulo">Condic.IVA:</td><td>{{entidad.get_fact_categFiscal_display|default_if_none:''}}</td>
      <td class="titulo">Domicilio:</td><td>{{ entidad.domicilio|default_if_none:'' }} - {{ entidad.cod_postal|default_if_none:'' }} - {{ entidad.localidad|default_if_none:'' }} - {{ entidad.get_provincia_display|default_if_none:'' }}</td>
    </tr>
    <tr>
      <td class="titulo">Teléfono/Celular:</td><td>{{entidad.telefono|default_if_none:''}} / {{ entidad.celular|default_if_none:'' }}</td>      
      <td class="titulo">E-mail Principal:</td><td>{{ entidad.email|default_if_none:'' }}</td>
    </tr>

    <tr>
      <td class="titulo">Contacto 1:</td><td colspan="3">{{entidad.contacto1_nombre|default_if_none:''}} {{ entidad.contacto1_email|default_if_none:'' }} {{ entidad.contacto1_tel|default_if_none:'' }} </td>            
    </tr>
    <tr>
      <td class="titulo">Contacto 2:</td><td colspan="3">{{entidad.contacto2_nombre|default_if_none:''}} {{ entidad.contacto2_email|default_if_none:'' }} {{ entidad.contacto2_tel|default_if_none:'' }} </td>            
    </tr>
    <tr>
      <td class="titulo">Contacto 3:</td><td colspan="3">{{entidad.contacto3_nombre|default_if_none:''}} {{ entidad.contacto3_email|default_if_none:'' }} {{ entidad.contacto3_tel|default_if_none:'' }} </td>            
    </tr>
    <tr>
      <td class="titulo">Contacto 4:</td><td colspan="3">{{entidad.contacto4_nombre|default_if_none:''}} {{ entidad.contacto4_email|default_if_none:'' }} {{ entidad.contacto4_tel|default_if_none:'' }} </td>            
    </tr>
    <tr>
      <td class="titulo">Contacto 5:</td><td colspan="3">{{entidad.contacto5_nombre|default_if_none:''}} {{ entidad.contacto5_email|default_if_none:'' }} {{ entidad.contacto5_tel|default_if_none:'' }} </td>            
    </tr>
    <tr>
      <td class="titulo">Detalle/Observaciones:</td><td colspan="3">{{entidad.observaciones|default_if_none:''}} </td>            
    </tr>

    </tbody>
  </table>
</div>                                 

          
<div class="modal-buttons">
    <div class="row">
        <div class="col-xs-6">
         <button data-dismiss="modal" class="btn btn-sm pull-left btn btn-danger" type="button">
              <i class="fa fa-times"></i>Cerrar
         </button>
        </div>       
      
      </div>    
</div>        
{% endblock main %}        

                               

templates/entidades/empresa_detalle.html
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block main %}    
<div class="row cerca">  
  <div class=" col-xs-12 "> 
  <fieldset>
    <table class="table table-striped table-hover table-condensed table-no-bordered tabla_detalle">
      <tbody>
      <tr>
        <td  class="titulo">Razón Social:</td><td colspan="3">{{e.razon_social|default_if_none:''}}</td>
      </tr>
      <tr>
        <td class="titulo">CUIT:</td><td>{{e.cuit|default_if_none:''}}</td>
        <td class="titulo">Cantidad Empleados:</td><td>{{e.cant_empleados|default_if_none:''}}</td>
      </tr>
      <tr>
        <td  class="titulo">Rubro:</td><td>{{e.rubro|default_if_none:''}}</td>
        <td class="titulo">Casa Central:</td><td>{{e.casa_central|default_if_none:''}}</td>
      </tr>
      <tr>
        <td  class="titulo">Domicilio:</td><td colspan="3">{{e.get_domicilio|default_if_none:''}}</td>
      </tr>
      <tr>
        <td class="titulo">Condic.IVA:</td><td>{{e.get_fact_categFiscal_display|default_if_none:''}}</td>
        <td class="titulo">IIBB:</td><td>{{e.iibb|default_if_none:''}}</td>      
      </tr>
      <tr>
        <td class="titulo">Teléfono/Celular:</td><td>{{e.telefono|default_if_none:''}} / {{ e.celular|default_if_none:'' }}</td>      
        <td class="titulo">E-mail:</td><td>{{ e.email|default_if_none:'' }}</td>
      </tr>

      <tr>
        <td class="titulo">ART:</td><td colspan="3">{{e.art|default_if_none:''}}</td>            
      </tr>
      <tr>
        <td class="titulo">Médico/Prof:</td><td colspan="3">{{e.medico_prof|default_if_none:''}}</td>            
      </tr>
      <tr>
        <td class="titulo">Contacto:</td><td >{{e.contacto_nombre|default_if_none:''}} </td>            
        <td class="titulo">Email:</td><td>{{e.contacto_email|default_if_none:''}}</td>
      </tr>
      <tr>
        <td class="titulo">Tel.:</td><td >{{e.contacto_tel|default_if_none:''}} </td>            
        <td class="titulo">Cargo/Profesión:</td><td>{{e.contacto_cargo|default_if_none:''}} / {{e.contacto_profesion|default_if_none:''}}</td>
      </tr>
      <tr>
        <td class="titulo">Detalle/Observaciones:</td><td colspan="3">{{e.observaciones|default_if_none:''}} </td>            
      </tr>
      <tr>
        <td class="titulo">Agrupamiento/Gerencia:</td><td colspan="3">{{e.agrupamiento|default_if_none:''}}</td>
      </tr>

      </tbody>
    </table>
  </fieldset>
  </div>                                 
</div>                 

          
<div class="modal-buttons">
    <div class="row">
        <div class="col-xs-6">
         <button data-dismiss="modal" class="btn btn-sm pull-left btn btn-danger" type="button">
              <i class="fa fa-times"></i>Cerrar
         </button>
        </div>              
      </div>    
</div>       
{% endblock main %}        

                               